### PR TITLE
ews_processor: add special case for group with sequence with choice

### LINKED ISSUE #2: unknown type WeeklyRecurrence
I started getting this error last week.

```
EWS question
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"><soap:Header><t:RequestServerVersion Version="Exchange2013_SP1"/><t:TimeZoneContext><t:TimeZoneDefinition Id="Central Standard Time"/></t:TimeZoneContext></soap:Header><soap:Body><m:UpdateItem MessageDisposition="SendAndSaveCopy" ConflictResolution="AutoResolve" SendMeetingInvitationsOrCancellations="SendToAllAndSaveCopy"><m:ItemChanges><t:ItemChange><t:ItemId Id="AAMkADViZDZkMmQxLTY2YTEtNGI5MC1iN2EzLTEyMzMwZTNlMmIwOABGAAAAAADKIXauCkX4R4LxBFsud0ANBwCdapcfDV6iQ62FKCJcjfRPAAAAAAENAACdapcfDV6iQ62FKCJcjfRPAAFd8B9lAAA=" ChangeKey="DwAAABYAAACdapcfDV6iQ62FKCJcjfRPAAFhjDVq"/><t:Updates><t:SetItemField><t:FieldURI FieldURI="calendar:Start"/><t:CalendarItem><t:Start>2018-03-27T08:00:00</t:Start></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:End"/><t:CalendarItem><t:End>2018-03-27T09:00:00</t:End></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:StartTimeZone"/><t:CalendarItem><t:StartTimeZone Id="Central Standard Time"></t:StartTimeZone></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:EndTimeZone"/><t:CalendarItem><t:EndTimeZone Id="Central Standard Time"></t:EndTimeZone></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:LegacyFreeBusyStatus"/><t:CalendarItem><t:LegacyFreeBusyStatus>Busy</t:LegacyFreeBusyStatus></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:IsAllDayEvent"/><t:CalendarItem><t:IsAllDayEvent>false</t:IsAllDayEvent></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="item:Sensitivity"/><t:Item><t:Sensitivity>Normal</t:Sensitivity></t:Item></t:SetItemField><t:SetItemField><t:ExtendedFieldURI PropertyTag="0x1000" PropertyType="String"/><t:Item><t:ExtendedProperty><t:ExtendedFieldURI PropertyTag="0x1000" PropertyType="String"/><t:Value>Created inside OWA
Updated in Outlook on 4/3





</t:Value></t:ExtendedProperty></t:Item></t:SetItemField><t:SetItemField><t:ExtendedFieldURI PropertyTag="0x37" PropertyType="String"/><t:Item><t:ExtendedProperty><t:ExtendedFieldURI PropertyTag="0x37" PropertyType="String"/><t:Value>HFC Systems call</t:Value></t:ExtendedProperty></t:Item></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:Location"/><t:CalendarItem><t:Location>Skype</t:Location></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:Recurrence"/><t:CalendarItem><t:Recurrence><t:WeeklyRecurrence><t:Interval>1</t:Interval><t:DaysOfWeek>Tuesday</t:DaysOfWeek></t:WeeklyRecurrence><t:NoEndRecurrence><t:StartDate>2018-03-27</t:StartDate></t:NoEndRecurrence></t:Recurrence></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:RequiredAttendees"/><t:CalendarItem><t:RequiredAttendees></t:RequiredAttendees></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="calendar:OptionalAttendees"/><t:CalendarItem><t:OptionalAttendees></t:OptionalAttendees></t:CalendarItem></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="item:ReminderIsSet"/><t:Item><t:ReminderIsSet>true</t:ReminderIsSet></t:Item></t:SetItemField><t:SetItemField><t:FieldURI FieldURI="item:ReminderMinutesBeforeStart"/><t:Item><t:ReminderMinutesBeforeStart>5</t:ReminderMinutesBeforeStart></t:Item></t:SetItemField><t:SetItemField><t:ExtendedFieldURI DistinguishedPropertySetId="PublicStrings" PropertyName="xmozlastack" PropertyType="String"/><t:Item><t:ExtendedProperty><t:ExtendedFieldURI DistinguishedPropertySetId="PublicStrings" PropertyName="xmozlastack" PropertyType="String"/><t:Value>20180424T141956Z</t:Value></t:ExtendedProperty></t:Item></t:SetItemField></t:Updates></t:ItemChange></m:ItemChanges></m:UpdateItem></soap:Body></soap:Envelope>
Ews Translator: Request Error: unknown type WeeklyRecurrence
```

### LINKED ISSUE #3: Serialization error - extra elements
I got this serialization error earlier today.

[serialization-exception.log](https://github.com/virtuald/ews-proxy/files/1986086/serialization-exception.log)

### PR DESCRIPTION
**Pull request by virtuald**
- Fixes #2
- Fixes #3 

@jschewebbn take a look and see if this addresses your issue. Most likely there are some aliasing issues (similar to your other transaction log).

### CODE REVIEW

**Comment by jschewebbn** [comment]
@virtuald when building I see warnings about duplicate element names. Presumably you see that as well. Is that likely what's causing the serialization problems in issue #4? Or is that something else?

**Comment by virtuald** [comment]
That's a new warning, it's normal. If the code ever gets refactored, then it will hopefully go away.

**Comment by jschewebbn** [comment]
OK, then this can be merged.

**Comment by virtuald** [comment]
Going to push a new update to it in a minute.

**Comment by virtuald** [comment]
@jschewebbn I can't remember if this addressed your issue or not, let me know if it should be merged

**Comment by jschewebbn** [comment]
I know it fixed #2. I don't think #3 is fixed though as we haven't figured out the deserialization error.

**Comment by jschewebbn** [comment]
I know it fixed #2. I don't think #3 is fixed though as we haven't figured out the deserialization error.

**Comment by jschewebbn** [comment]
I looked back in my error logs and I was running this branch for awhile and I'm still getting serialization exceptions.

**Pull request merged**
